#!/bin/bash

export SERVER_LOCAL_HOST=172.17.0.1
export SERVER_LOCAL_USER=
export DATABASE_USERNAME=
export DATABASE_PASSWORD=

# Ports
export SMART_SHELL_POSTGRES_PORT=10001
export SMART_SHELL_REDIS_PORT=10002
export SMART_SHELL_MONGO_PORT=10003
export SMART_SHELL_SPRINGBOOT_PORT=10004
export SMART_SHELL_ANGULAR_PORT=10005