services:
  app-postgres:
    container_name: smart-shell-production-postgres
    image: luis122448/smart-shell-postgres:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: $SMART_SHELL_PRODUCTION_POSTGRES_USERNAME
      POSTGRES_PASSWORD: $SMART_SHELL_PRODUCTION_POSTGRES_PASSWORD
      POSTGRES_DB: $SMART_SHELL_PRODUCTION_POSTGRES_DATABASE
    ports:
      - "${SMART_SHELL_PRODUCTION_POSTGRES_PORT}:5432"
    volumes:
      - ${DATA_STORAGE_PATH}/smart-shell-postgres/data:/var/lib/postgresql/data
      - ${DATA_STORAGE_PATH}/smart-shell-postgres/logs:/opt/logs
      - ${DATA_STORAGE_PATH}/smart-shell-postgres/backups:/opt/backups
      - ${DATA_STORAGE_PATH}/smart-shell-postgres/configurations:/opt/configurations
    networks:
      - smart-shell-network
    restart: unless-stopped

  app-mongo:
    container_name: smart-shell-production-mongo
    image: luis122448/smart-shell-mongo:latest
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $SMART_SHELL_PRODUCTION_MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $SMART_SHELL_PRODUCTION_MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $SMART_SHELL_PRODUCTION_MONGO_DATABASE
    ports:
      - "${SMART_SHELL_PRODUCTION_MONGO_PORT}:27017"
    volumes:
      - ${DATA_STORAGE_PATH}/smart-shell-mongo/data:/data/db
    networks:
      - smart-shell-network
    restart: unless-stopped

  app-redis:
    container_name: smart-shell-production-redis
    image: luis122448/smart-shell-redis:latest
    env_file:
      - ./.env
    environment:
      SMART_SHELL_PRODUCTION_REDIS_PASSWORD: ${SMART_SHELL_PRODUCTION_REDIS_PASSWORD}
    ports:
      - "${SMART_SHELL_PRODUCTION_REDIS_PORT}:6379"
    networks:
      - smart-shell-network
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${SMART_SHELL_PRODUCTION_REDIS_PASSWORD}
    restart: unless-stopped

  app-springboot:
    container_name: smart-shell-production-springboot
    image: luis122448/smart-shell-springboot:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: $SMART_SHELL_PRODUCTION_POSTGRES_HOST
      POSTGRES_PORT: $SMART_SHELL_PRODUCTION_POSTGRES_PORT_INTERNAL
      POSTGRES_DATABASE: $SMART_SHELL_PRODUCTION_POSTGRES_DATABASE
      POSTGRES_USERNAME: $SMART_SHELL_PRODUCTION_POSTGRES_USERNAME
      POSTGRES_PASSWORD: $SMART_SHELL_PRODUCTION_POSTGRES_PASSWORD
      MONGO_HOST: $SMART_SHELL_PRODUCTION_MONGO_HOST
      MONGO_PORT: $SMART_SHELL_PRODUCTION_MONGO_PORT_INTERNAL
      MONGO_DATABASE: $SMART_SHELL_PRODUCTION_MONGO_DATABASE
      MONGO_USERNAME: $SMART_SHELL_PRODUCTION_MONGO_USERNAME
      MONGO_PASSWORD: $SMART_SHELL_PRODUCTION_MONGO_PASSWORD
      REDIS_HOST: $SMART_SHELL_PRODUCTION_REDIS_HOST
      REDIS_PORT: $SMART_SHELL_PRODUCTION_REDIS_PORT_INTERNAL
      REDIS_USERNAME: $SMART_SHELL_PRODUCTION_REDIS_USERNAME
      REDIS_PASSWORD: $SMART_SHELL_PRODUCTION_REDIS_PASSWORD
      CORS_ALLOWED_ORIGINS: $CORS_ALLOWED_ORIGINS
    ports:
      - "${SMART_SHELL_PRODUCTION_SPRINGBOOT_PORT}:8080"
    depends_on:
      - app-postgres
      - app-mongo
      - app-redis
    networks:
      - smart-shell-network
    restart: unless-stopped
  
  app-angular:
    container_name: smart-shell-production-angular
    image: luis122448/smart-shell-angular:latest
    env_file:
      - ./.env
    environment:
      API_URL: $API_URL
      HEALTH_CHECK_URL: $HEALTH_CHECK_URL
    ports:
      - "${SMART_SHELL_PRODUCTION_ANGULAR_PORT}:80"
    depends_on:
      - app-springboot
    networks:
      - smart-shell-network
    restart: unless-stopped

networks:
  smart-shell-network:
    external: false
    driver: bridge