apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  namespace: smart-shell-production
  labels:
    app: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angular
          image: luis122448/smart-shell-angular:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: smart-shell-config
