apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: smart-shell-production
  labels:
    app: postgres-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-service
