apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: smart-shell-production
  labels:
    app: redis-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-service
