apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: smart-shell-production
  labels:
    app: springboot-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: springboot-service
